### Import NumPy

In [2]:
import numpy as np 
import pandas as pd

### Basics 

In [4]:
a = np.array([1,2,3,])
print(a)

[1 2 3]


In [7]:
b = np.array([[23.0,10.0,2003.0],[17.0,9.0,2000.0]])
print(b)

[[  23.   10. 2003.]
 [  17.    9. 2000.]]


#### Get (np.array) Dimension 

In [11]:
a.ndim

1

In [10]:
b.ndim

2

#### Get (np.array) Shape 

In [12]:
a.shape

(3,)

In [13]:
b.shape

(2, 3)

#### Get (np.array) Data Type 

In [14]:
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('float64')

### Accessing/Changing specific elements, rows, columns, etc

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#### Get a specific element [r, c]

In [18]:
# Get 13 from the array 
a[1, -2]
a[1, 5]

13

In [20]:
# Get a entire first row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a entire fifth row 
a[:, -3]
a[:, 4]

array([ 5, 12])

In [24]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# More complex indexing [start:end:stepsize]
# Ex: Get every even number between (2,6)

a[0, 1:6:2]

array([2, 4, 6])

In [28]:
# Ex: Get every odd number from the second row 

a[1,1:-1:2]

array([ 9, 11, 13])

#### Change a specific element

In [29]:
# Set the 4th element of second row to (155)

a[1,5] = 155
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 155  14]]


In [42]:
# Change an entire specific column values 
# Set the 1st column values to (17,9)
a[:,0] = [17,9]
print(a)

[[ 17  23   3   5   5   6   7]
 [  9  10  10   5  12 155  14]]


In [43]:
# Set the 2nd column values to (3,4)
a[:,1] = [23,10]
print(a)

[[ 17  23   3   5   5   6   7]
 [  9  10  10   5  12 155  14]]


### 3D Example 

In [51]:
b = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12], [13,14,15,16]]])
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [52]:
b.ndim

3

In [55]:
# Get a specific element (work outside in) index: [Which set do you want, Which Row, element]
# Get the before last element for the second set 

b[1,1,-2]

15

In [57]:
# Get the very second element from the first set 
b[0,0,1]

2

In [61]:
# Get the third element from the second row from the first set 
b[0,1,2]

7

In [64]:
# Get an entire set from the array 
b[0,:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Get an entire row from the set 
b[1,0,:]

array([ 9, 10, 11, 12])

In [66]:
# Get an entire column from the set 
b[1,:,2]

array([11, 15])

In [70]:
# Replace values
# Replace First Row - Second Set = [17,9,23,10]
b[1,0,:] = [17,9,23,10]
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[17,  9, 23, 10],
        [13, 14, 15, 16]]])

### Initializing Different Types of Arrays 

In [72]:
# All 0s matrix 
np.zeros((3,3)) #2D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
# All 0s matrix 
np.zeros((3,2,3)) #3D

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [81]:
# All 1s matrix
ones_mx = np.ones((2,2,4), dtype= 'float' #Specifing the Data Type) 
ones_mx

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [82]:
ones_mx.dtype

dtype('float64')

In [83]:
# Any other number 
np.full((3,4), 23)

array([[23, 23, 23, 23],
       [23, 23, 23, 23],
       [23, 23, 23, 23]])

In [84]:
# Any other number (full_like)
np.full_like(b, 3)

array([[[3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [85]:
# Random decimal numbers 
np.random.rand(4,2)

array([[0.17683729, 0.71536013],
       [0.31638065, 0.1789104 ],
       [0.31970794, 0.7986528 ],
       [0.24297443, 0.9167917 ]])

In [86]:
# Random integer numbers 
np.random.randint(10, size= (3,4))

array([[2, 0, 8, 7],
       [5, 7, 8, 9],
       [9, 2, 3, 9]])

In [87]:
# The identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
# Repeat array 
arr = np.array([[23,10,2003]])
r1 = np.repeat(arr,4, axis= 0)
r1

array([[  23,   10, 2003],
       [  23,   10, 2003],
       [  23,   10, 2003],
       [  23,   10, 2003]])

### Quiz

In [96]:
# Using all of above make an array that looks like 
# 1, 1, 1, 1, 1
# 1, 0, 0, 0, 1
# 1, 0, 9, 0, 1
# 1, 0, 0, 0, 1
# 1, 1, 1, 1, 1

In [92]:
# The long way 

ex = np.full((5,5), 1)
ex

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [95]:
ex[1,1:4] = [0]
ex

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [97]:
ex[-2,1:4] = [0]
ex

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [100]:
ex[2,1:4] = 0
ex

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [101]:
ex[2,2] = 9
ex

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [112]:
# The Fast Way 

ans = np.ones((5,5))
ans

z = np.zeros((3,3))
z
z[1,1] = 9
z

ans[1:4,1:4] = z
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be Careful When Coping Arrays ! 

In [117]:
a = np.array([1,2,3])
b = a # Making a copy of "a"
# Now if you wanna replace an element on "b" array it will be replaced on "a" Too 
# So what can we do ? 
a = np.array([1,2,3])
b = a.copy() #we just add copy() attribute 
b[1] = 555
b

array([  1, 555,   3])

In [118]:
a 

array([1, 2, 3])

## Mathimatics on NumPy

In [120]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [127]:
print(a + 2)
# It will add 2 to each element 
# So as the other operators mathimatical operatiors 

[3 4 5 6 7]


In [132]:
# Operations between full arrays
b = np.array([10,10,10,10,10])
print(a+b)

[11 12 13 14 15]


In [137]:
# Take (sin, cos, tan)
np.sin(a)
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

## Liner Algebra on NumPy

In [145]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 3)
print (b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


In [150]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

In [156]:
# Find the determinant 
c = np.identity(6)
np.linalg.det(c)

1.0

## Statistics on NumPy 


In [172]:
# MIN, MAX, MID, STD, VAR...etc
a = np.random.randint(10, size= (3,4))
minimum = np.min(a)
maximum = np.max(a)
median = np.median(a)
standard_deviation = np.std(a)
variance = np.var(a)
print ({'MIN': minimum, 'MAX': maximum, 'MID': median, 'STD': standard_deviation, 'VAR': variance})

{'MIN': 0, 'MAX': 9, 'MID': 6.0, 'STD': 3.362373500305336, 'VAR': 11.305555555555557}


In [176]:
a

array([[0, 7, 9, 0],
       [6, 8, 8, 6],
       [6, 1, 0, 7]])

In [178]:
# Sum all of the elements on the array by column "Columns Total"
np.sum(a, axis= 0)

array([12, 16, 17, 13])

## Reorganizing Arrays 

In [188]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [195]:
# Vertically staking vectors 
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

np.vstack([v1,v2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [196]:
# Horizontally staking vectors 
h1 = np.array([1,2,3,4,5])
h2 = np.array([6,7,8,9,10])

np.hstack([h1,h2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Miscellaneous

#### Load Data from File 

In [210]:
loaded = np.genfromtxt(r"C:\Users\media\Desktop\ArrayToImport.txt", delimiter= ',', dtype= 'int')
print(loaded)

[[0 4 4 2 2 1 4 0 0 0]
 [2 2 3 1 2 4 4 0 2 2]
 [1 3 1 3 0 2 1 1 3 0]
 [4 4 1 3 3 0 2 0 3 2]]


## Boolean Masking and Advanced Indexing 

In [214]:
ar = loaded[loaded > 2]
print(ar)

[4 4 4 3 4 4 3 3 3 4 4 3 3 3]


In [225]:
np.any(loaded>2, axis= 0)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False])

In [224]:
# You also can index with a list in NumPy
a = np.array([1,2,3,8,9,10,11,12,4,5,6,7,8,9,10,11,12,13,14])
a[[1,10,6,12]]

array([ 2,  6, 11,  8])

In [229]:
# Conditional Indeixing 
n = ((loaded < 3) & (loaded > 1))
print(n)
# Reverse 
r = (~((loaded < 3) & (loaded > 1)))
print(r)

[[False False False  True  True False False False False False]
 [ True  True False False  True False False False  True  True]
 [False False False False False  True False False False False]
 [False False False False False False  True False False  True]]
[[ True  True  True False False  True  True  True  True  True]
 [False False  True  True False  True  True  True False False]
 [ True  True  True  True  True False  True  True  True  True]
 [ True  True  True  True  True  True False  True  True False]]


## Final Quiz 


In [244]:
# Using all of above make an array that looks like 
a= np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25], [26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [245]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [246]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [254]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [257]:
# My Linkedin Account: https://www.linkedin.com/in/yousef-elbehiry
# Maven Analytics: https://mavenanalytics.io/profile/Yousef-Elbehiry/181994400